In [1]:
import pandas as pd
import numpy as np
import codecs
from scipy import linalg

import make_database as md
import make_bit_frame as mbf
import make_distance_matrix as mdm
import generate_controler as gc
from AIC import *

import glob
import copy
from __future__ import division

In [9]:
fileList = glob.glob('./csvFileList/*.csv')
gcc = gc.GenerateControler(fileList, "./InputValueDB/母音入力数値一覧.csv", "./InputValueDB/子音入力数値一覧.csv")

In [11]:
gcc.mainPreProccess()

In [13]:
cons_col = (gcc.cons.columns == "子音").tolist().index(True)
# 最初の調音アライメント列 (母音も同じ)
first_columns = (gcc.cons.columns == "位置").tolist().index(True)

#locate_index = (self.table.T.iloc[cons_col, :] == ).tolist().index(True)
try:
    nan_position = (gcc.cons.T.iloc[cons_col, :] == gcc.cons.T.iloc[cons_col, :]).tolist().index(False)
    index_size = nan_position
except Exception as e:
    index_size = gcc.cons.index.size
    
art_lists = []
name_lists = []
for kk in range(0, index_size):
    art_lists.append(gcc.cons.loc[kk][first_columns:first_columns + 5].tolist())
    name_lists.append(gcc.cons.loc[kk][cons_col])

mDM = mdm.MakeDistanceMatrix()
mDM.makeHammDistanceFrame(art_lists)
cons_data_frame = mDM.getDistanceFrame()

In [14]:
pd.DataFrame(cons_data_frame, name_lists, name_lists).to_csv('./SpecificCSVFiles/distance/cons_dis.csv', sep=',')

In [15]:
vowel_col = (gcc.vowel.columns == "母音").tolist().index(True)
# 最初の調音アライメント列 (母音も同じ)
first_columns = (gcc.vowel.columns == "長さ").tolist().index(True)

#locate_index = (self.table.T.iloc[cons_col, :] == ).tolist().index(True)
try:
    nan_position = (gcc.vowel.T.iloc[vowel_col, :] == gcc.vowel.T.iloc[vowel_col, :]).tolist().index(False)
    index_size = nan_position
except Exception as e:
    index_size = gcc.vowel.index.size
    
art_lists = []
name_lists = []
for kk in range(0, index_size):
    art_lists.append(gcc.vowel.loc[kk][first_columns:first_columns + 5].tolist())
    name_lists.append(gcc.vowel.loc[kk][vowel_col])

mDM = mdm.MakeDistanceMatrix()
mDM.makeHammDistanceFrame(art_lists)
vowel_data_frame = mDM.getDistanceFrame()

In [16]:
pd.DataFrame(vowel_data_frame, name_lists, name_lists).to_csv('./SpecificCSVFiles/distance/vowel_dis.csv', sep=',')

In [12]:
gcc.vowel

,Unnamed: 0,母音,長さ,口の開き,舌の位置,唇の状態,無声鼻音,母音.1,長さ.1,口の開き.1,舌の位置.1,唇の状態.1,無声鼻音.1,Unnamed: 13
0,10000000000000000000000000000000000000000000001,y,100000010,1000010,110000,1010,11,y,10000001,100001,11000,101,101,NaN
1,10000000000000000000000000000000000000000000010,i,100000010,1000010,100010,1010,11,i,10000001,100001,10001,101,101,NaN
2,10000000000000000000000000000000000000000000100,i2,100000010,1000010,100100,1010,11,i2,10000001,100001,10010,101,101,NaN
3,10000000000000000000000000000000000000000001000,e,100000010,1100000,100010,1010,11,e,10000001,110000,10001,101,101,NaN
4,10000000000000000000000000000000000000000010000,e2,100000010,1100000,100100,1010,11,e2,10000001,110000,10010,101,101,NaN
5,10000000000000000000000000000000000000000100000,a,100000010,1010000,101000,1010,11,a,10000001,101000,10100,101,101,NaN
6,10000000000000000000000000000000000000001000000,o,100000010,1100000,101000,1100,11,o,10000001,110000,10100,110,101,NaN
7,10000000000000000000000000000000000000010000000,u,100000010,1000010,101000,1100,11,u,10000001,100001,10100,110,101,NaN
8,10000000000000000000000000000000000000100000000,o2,100000010,1000100,100100,1100,11,o2,10000001,100010,10010,110,101,NaN
9,10000000000000000000000000000000000001000000000,y:,100000100,1000010,110000,1010,11,y:,10000010,100001,11000,101,101,NaN
10,10000000000000000000000000000000000010000000000,yy,100000100,1000010,110000,1010,11,yy,10000010,100001,11000,101,101,NaN
11,10000000000000000000000000000000000100000000000,yq,100001000,1000010,110000,1010,11,yq,10000100,100001,11000,101,101,NaN
12,10000000000000000000000000000000001000000000000,yn,100010000,1000010,110000,1010,11,yn,10001000,100001,11000,101,101,NaN
13,10000000000000000000000000000000010000000000000,i:,100000100,1000010,100010,1010,11,i:,10000010,100001,10001,101,101,NaN
14,10000000000000000000000000000000100000000000000,ii,100000100,1000010,100010,1010,11,ii,10000010,100001,10001,101,101,NaN
15,10000000000000000000000000000001000000000000000,iq,100001000,1000010,100010,1010,11,iq,10000100,100001,10001,101,101,NaN
16,10000000000000000000000000000010000000000000000,in,100010000,1000010,100010,1010,11,in,10001000,100001,10001,101,101,NaN
17,10000000000000000000000000000100000000000000000,i2:,100000100,1000010,100100,1010,11,i2:,10000010,100001,10010,101,101,NaN
18,10000000000000000000000000001000000000000000000,i2i2,100000100,1000010,100100,1010,11,i2i2,10000010,100001,10010,101,101,NaN
19,10000000000000000000000000010000000000000000000,i2q,100001000,1000010,100100,1010,11,i2q,10000100,100001,10010,101,101,NaN
20,10000000000000000000000000100000000000000000000,i2n,100010000,1000010,100100,1010,11,i2n,10001000,100001,10010,101,101,NaN
21,10000000000000000000000001000000000000000000000,e:,100000100,1100000,100010,1010,11,e:,10000010,110000,10001,101,101,NaN
22,10000000000000000000000010000000000000000000000,ee,100000100,1100000,100010,1010,11,ee,10000010,110000,10001,101,101,NaN
23,10000000000000000000000100000000000000000000000,eq,100001000,1100000,100010,1010,11,eq,10000100,110000,10001,101,101,NaN
24,10000000000000000000001000000000000000000000000,en,100010000,1100000,100010,1010,11,en,10001000,110000,10001,101,101,NaN
25,10000000000000000000010000000000000000000000000,e2:,100000100,1100000,100100,1010,11,e2:,10000010,110000,10010,101,101,NaN
26,10000000000000000000100000000000000000000000000,e2e2,100000100,1100000,100100,1010,11,e2e2,10000010,110000,10010,101,101,NaN
27,10000000000000000001000000000000000000000000000,e2q,100001000,1100000,100100,1010,11,e2q,10000100,110000,10010,101,101,NaN
28,10000000000000000010000000000000000000000000000,e2n,100010000,1100000,100100,1010,11,e2n,10001000,110000,10010,101,101,NaN
29,10000000000000000100000000000000000000000000000,a:,100000100,1010000,101000,1010,11,a:,10000010,101000,10100,101,101,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,10000000000000100000000000000000000000000000000,an,100010000,1010000,101000,1010,11,an,10001000,101000,10100,101,101,NaN
33,10000000000001000000000000000000000000000000000,ai,100100000,1000010,100010,1010,11,ai,10010000,100001,10001,101,101,NaN
34,10000000000010000000000000000000000000000000000,o:,100000100,1100000,101000,1100,11,o:,10000010,110000,10100,110,101,NaN
35,10000000000100000000000000000000000000000000000,oo,100000100,1100000,101000,1100,11,oo,10000010,110000,10100,110,101,NaN
36,10000000001000000000000000000000000000000000000,oq,100001000,1100000,101000,1100,11,oq,10000100,110000,10100,110,101,NaN
37,10000000010000000000000000000000000000000000000,on,100010000,1100000,101000,1100,11,on,10001000,110000,10100,110,101,NaN
38,10000000100000000000000000000000000000000000000,u:,100000100,1000010,101000,1100,11,u:,10000010,100001,10100,110,101,NaN
39,10000001000000000000000000000000000000000000000,uu,100000100,1000010,101000,1100,11,uu,10000010,100001,10100,110,101,NaN
40,10000010000000000000000000000000000000000000000,uq,100001000,1000010,101000,1100,11,uq,10000100,100001,10100,110,101,NaN
41,10000100000000000000000000000000000000000000000,un,100010000,1000010,101000,1100,11,un,10001000,100001,10100,110,101,NaN
42,10001000000000000000000000000000000000000000000,ui,100100000,1000010,100010,1010,11,ui,10010000,100001,10001,101,101,NaN
43,10010000000000000000000000000000000000000000000,u:q,110000000,1000010,100010,1010,11,u:q,11000000,100001,10001,101,101,NaN
44,10100000000000000000000000000000000000000000000,o:q,110000000,1100000,101000,1100,11,o:q,11000000,110000,10100,110,101,NaN
45,11000000000000000000000000000000000000000000000,-1,100000000,1000000,100000,1000,10,-1,00000000,000000,00000,000,000,NaN
46,???????????????????????????????????????????????,-9,?????????,???????,??????,????,??,-9,????????,??????,?????,???,???,NaN
47,...............................................,.,.........,.......,......,....,..,.,.,.,.,.,.,NaN
48,min,NaN,-9,-9,-9,-9,-9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,max,NaN,7,5,4,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.,.,.,.,.,.,NaN
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-9,????????,??????,?????,???,???,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,00000000,000000,00000,000,000,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,101,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10000001,100001,10001,101,110,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,10000010,100010,10010,110,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,10000100,100100,10100,NaN,NaN,NaN
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,10001000,101000,11000,NaN,NaN,NaN
59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,10010000,110000,NaN,NaN,NaN,NaN
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,10100000,NaN,NaN,NaN,NaN,NaN
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,11000000,NaN,NaN,NaN,NaN,NaN